#!/usr/bin/env python3
import json
import sys
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import os

def generate_report(output_path, data):
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        title="Oupweb Dashboard Report",
        author="Z.ai",
        creator="Z.ai"
    )
    
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=28,
        alignment=TA_CENTER,
        spaceAfter=12
    )
    
    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontSize=14,
        alignment=TA_CENTER,
        textColor=colors.gray,
        spaceAfter=30
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        spaceBefore=20,
        spaceAfter=10
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=12,
        spaceBefore=6,
        spaceAfter=6
    )
    
    story = []
    
    story.append(Paragraph("OUPWEB", title_style))
    story.append(Paragraph(data.get('title', 'Dashboard Report'), subtitle_style))
    story.append(Paragraph(data.get('date', ''), ParagraphStyle('Date', parent=styles['Normal'], fontSize=10, alignment=TA_CENTER, textColor=colors.gray)))
    story.append(Spacer(1, 0.3*inch))
    
    summary_title = data.get('summaryTitle', 'SUMMARY')
    story.append(Paragraph(summary_title, heading_style))
    
    summary_data = [
        [data.get('productsLabel', 'Products'), str(data.get('productsCount', 0))],
        [data.get('activeLabel', 'Active Products'), str(data.get('activeCount', 0))],
        [data.get('tasksLabel', 'Tasks'), str(data.get('tasksCount', 0))],
        [data.get('completedLabel', 'Completed Tasks'), str(data.get('completedCount', 0))],
    ]
    
    summary_table = Table(summary_data, colWidths=[3*inch, 2*inch])
    summary_table.setStyle(TableStyle([
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 0.3*inch))
    
    priority_title = data.get('priorityTitle', 'TASKS BY PRIORITY')
    story.append(Paragraph(priority_title, heading_style))
    
    priority_data = [
        [data.get('highLabel', 'High Priority'), str(data.get('highCount', 0))],
        [data.get('mediumLabel', 'Medium Priority'), str(data.get('mediumCount', 0))],
        [data.get('lowLabel', 'Low Priority'), str(data.get('lowCount', 0))],
    ]
    
    priority_table = Table(priority_data, colWidths=[3*inch, 2*inch])
    priority_table.setStyle(TableStyle([
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(priority_table)
    story.append(Spacer(1, 0.3*inch))
    
    products_list_title = data.get('productsListTitle', 'PRODUCTS LIST')
    story.append(Paragraph(products_list_title, heading_style))
    
    products = data.get('products', [])
    if products:
        header = ['Name', 'Price', data.get('stockLabel', 'Stock')]
        product_rows = [header]
        for p in products[:15]:
            product_rows.append([
                p.get('name', 'Unknown')[:30],
                f"${p.get('price', 0):.2f}",
                str(p.get('stock', 0))
            ])
        
        products_table = Table(product_rows, colWidths=[3.5*inch, 1.25*inch, 1.25*inch])
        products_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F5F5F5')]),
        ]))
        story.append(products_table)
    
    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph(data.get('generatedBy', 'Generated by Oupweb Dashboard'), 
                          ParagraphStyle('Footer', parent=styles['Normal'], fontSize=9, textColor=colors.gray, alignment=TA_CENTER)))
    
    doc.build(story)
    return output_path

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Usage: python generate_pdf.py <output_path> <json_data>")
        sys.exit(1)
    
    output_path = sys.argv[1]
    json_data = json.loads(sys.argv[2])
    
    result = generate_report(output_path, json_data)
    print(result)
