import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { exec } from 'child_process';
import { promisify } from 'util';
import { readFile, unlink } from 'fs/promises';
import path from 'path';

const execAsync = promisify(exec);

export async function GET(request: NextRequest) {
  let tempPdfPath = '';
  
  try {
    const searchParams = request.nextUrl.searchParams;
    const language = searchParams.get('lang') || 'en';
    
    const [products, tasks] = await Promise.all([
      db.product.findMany({ orderBy: { createdAt: 'desc' } }),
      db.task.findMany({ orderBy: { createdAt: 'desc' } }),
    ]);

    const activeProducts = products.filter(p => p.isActive).length;
    const doneTasks = tasks.filter(t => t.status === 'done').length;
    const highPriority = tasks.filter(t => t.priority === 'high').length;
    const mediumPriority = tasks.filter(t => t.priority === 'medium').length;
    const lowPriority = tasks.filter(t => t.priority === 'low').length;

    const now = new Date();
    const dateStr = now.toLocaleDateString(language === 'fr' ? 'fr-FR' : 'en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });

    const isFrench = language === 'fr';
    
    const reportData = {
      title: isFrench ? 'RAPPORT TABLEAU DE BORD' : 'DASHBOARD REPORT',
      date: dateStr,
      summaryTitle: isFrench ? 'RESUME' : 'SUMMARY',
      productsLabel: isFrench ? 'Produits' : 'Products',
      productsCount: products.length,
      activeLabel: isFrench ? 'Produits actifs' : 'Active Products',
      activeCount: activeProducts,
      tasksLabel: isFrench ? 'Taches' : 'Tasks',
      tasksCount: tasks.length,
      completedLabel: isFrench ? 'Taches terminees' : 'Completed Tasks',
      completedCount: doneTasks,
      priorityTitle: isFrench ? 'TACHES PAR PRIORITE' : 'TASKS BY PRIORITY',
      highLabel: isFrench ? 'Haute priorite' : 'High Priority',
      highCount: highPriority,
      mediumLabel: isFrench ? 'Priorite moyenne' : 'Medium Priority',
      mediumCount: mediumPriority,
      lowLabel: isFrench ? 'Basse priorite' : 'Low Priority',
      lowCount: lowPriority,
      productsListTitle: isFrench ? 'LISTE DES PRODUITS' : 'PRODUCTS LIST',
      stockLabel: isFrench ? 'Stock' : 'Stock',
      products: products.slice(0, 15).map(p => ({ 
        name: p.name, 
        price: p.price, 
        stock: p.stock 
      })),
      generatedBy: isFrench ? 'Genere par Oupweb Dashboard' : 'Generated by Oupweb Dashboard',
    };

    const timestamp = Date.now();
    tempPdfPath = path.join('/tmp', `oupweb-report-${timestamp}.pdf`);
    const scriptPath = path.join(process.cwd(), 'mini-services', 'pdf-service', 'generate_pdf.py');
    
    await execAsync(`python3 "${scriptPath}" "${tempPdfPath}" '${JSON.stringify(reportData).replace(/'/g, "'\"'\"'")}'`);
    
    const pdfBuffer = await readFile(tempPdfPath);
    
    const filename = `oupweb-report-${new Date().toISOString().split('T')[0]}.pdf`;
    
    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  } catch (error) {
    console.error('Report generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate report' },
      { status: 500 }
    );
  } finally {
    if (tempPdfPath) {
      try {
        await unlink(tempPdfPath);
      } catch {
        // ignore cleanup errors
      }
    }
  }
}
